# Generated by Django 6.0.1 on 2026-01-31 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.TextField()),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('administrador', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='users_usernam_baeb4b_idx'), models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['created_at'], name='users_created_6541e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('what_is_done', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En Progreso'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('has_phases', models.BooleanField(default=False)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=200)),
                ('phase_number', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('objectives', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='webAMG.project')),
            ],
            options={
                'verbose_name': 'Fase de Proyecto',
                'verbose_name_plural': 'Fases de Proyectos',
                'db_table': 'project_phases',
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity_type', models.CharField(choices=[('entrega', 'Entrega'), ('capacitacion', 'Capacitación'), ('instalacion', 'Instalación'), ('visita', 'Visita'), ('reunion', 'Reunión'), ('seguimiento', 'Seguimiento'), ('mantenimiento', 'Mantenimiento'), ('evaluacion', 'Evaluación'), ('otro', 'Otro')], max_length=20)),
                ('description', models.TextField()),
                ('participants_count', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='webAMG.project')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='webAMG.projectphase')),
            ],
            options={
                'verbose_name': 'Actividad Diaria',
                'verbose_name_plural': 'Actividades Diarias',
                'db_table': 'daily_activities',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuarios',
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('municipality', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('community', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_place', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('cui_dpi', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('civil_status', models.CharField(blank=True, choices=[('soltero', 'Soltero'), ('casado', 'Casado'), ('unido', 'Unido'), ('separado', 'Separado'), ('divorciado', 'Divorciado'), ('viudo', 'Viudo')], max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, choices=[('maya', 'Maya'), ('garifuna', 'Garifuna'), ('xinca', 'Xinca'), ('afrodescendiente', 'Afrodescendiente'), ('mestizo', 'Mestizo'), ('extranjero', 'Extranjero')], max_length=20, null=True)),
                ('linguistic_community', models.CharField(blank=True, max_length=100, null=True)),
                ('household_type', models.CharField(blank=True, choices=[('unipersonal_nuclear', 'Unipersonal/Nuclear'), ('extensa', 'Extensa'), ('compuesta', 'Compuesta'), ('co_residentes', 'Co-residentes')], max_length=20, null=True)),
                ('total_household_members', models.IntegerField(default=0)),
                ('male_members', models.IntegerField(default=0)),
                ('female_members', models.IntegerField(default=0)),
                ('profile_image_url', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'db_table': 'beneficiaries',
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='beneficiari_first_n_9a9ced_idx'), models.Index(fields=['cui_dpi'], name='beneficiari_cui_dpi_b27345_idx'), models.Index(fields=['department'], name='beneficiari_departm_c24665_idx'), models.Index(fields=['municipality'], name='beneficiari_municip_b4092f_idx'), models.Index(fields=['community'], name='beneficiari_communi_7b05f7_idx'), models.Index(fields=['birth_date'], name='beneficiari_birth_d_9a5f79_idx'), models.Index(fields=['is_active'], name='beneficiari_is_acti_c9a840_idx'), models.Index(fields=['created_by'], name='beneficiari_created_2bc39f_idx'), models.Index(fields=['created_at'], name='beneficiari_created_974592_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Login',
                'verbose_name_plural': 'Logs de Login',
                'db_table': 'login_log',
                'indexes': [models.Index(fields=['user'], name='login_log_user_id_309b1c_idx'), models.Index(fields=['login_time'], name='login_log_login_t_82cb4b_idx'), models.Index(fields=['success'], name='login_log_success_80e93a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='projects_project_cceb9a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_status_6303d7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date', 'end_date'], name='projects_start_d_cb24a6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_by'], name='projects_created_428cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['responsible_user'], name='projects_respons_f22854_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['municipality'], name='projects_municip_77d296_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['department'], name='projects_departm_0915a7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['project'], name='project_pha_project_0badd5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['status'], name='project_pha_status_647031_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['start_date', 'end_date'], name='project_pha_start_d_d6558b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['project', 'phase_number'], name='project_pha_project_a1c5c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectphase',
            unique_together={('project', 'phase_number')},
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['project'], name='daily_activ_project_f66bae_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['phase'], name='daily_activ_phase_i_b44fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['activity_date'], name='daily_activ_activit_ebab6d_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['activity_type'], name='daily_activ_activit_510546_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['created_by'], name='daily_activ_created_523a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='user_sessio_user_id_eb20aa_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_token'], name='user_sessio_session_baddb8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='user_sessio_expires_66ae96_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active'], name='user_sessio_is_acti_1b3cb1_idx'),
        ),
    ]
