# Generated by Django 6.0.1 on 2026-02-01 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAMG', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='beneficiary',
            new_name='beneficiari_created_266432_idx',
            old_name='beneficiari_created_2bc39f_idx',
        ),
        migrations.RenameIndex(
            model_name='dailyactivity',
            new_name='daily_activ_created_508b1e_idx',
            old_name='daily_activ_created_523a9c_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_created_83d3c9_idx',
            old_name='projects_created_428cb1_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='projects_respons_8e2ed9_idx',
            old_name='projects_respons_f22854_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='Proyectos/FotosPortada/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_user',
            field=models.ForeignKey(blank=True, db_column='responsible_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
