# Generated by Django 6.0.1 on 2026-02-06 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAMG', '0003_phase_evidence_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('requirements', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evidencia de Proyecto',
                'verbose_name_plural': 'Evidencias de Proyectos',
                'db_table': 'project_evidences',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material de Proyecto',
                'verbose_name_plural': 'Materiales de Proyectos',
                'db_table': 'project_materials',
            },
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='profile_image_url',
        ),
        migrations.RemoveField(
            model_name='dailyactivity',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='projectphase',
            name='objectives',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='dpi_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phaseevidence',
            name='requirements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='community',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='actual_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='ActivityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('photo_order', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webAMG.dailyactivity')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Actividad',
                'verbose_name_plural': 'Fotos de Actividades',
                'db_table': 'activity_photos',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('operation', models.CharField(db_index=True, max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'audit_log',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryEconomy',
            fields=[
                ('beneficiary', models.OneToOneField(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='economy', serialize=False, to='webAMG.beneficiary')),
                ('economically_active_employed', models.BooleanField(default=False)),
                ('economically_active_independent', models.BooleanField(default=False)),
                ('economically_active_entrepreneur', models.BooleanField(default=False)),
                ('economically_active_day_laborer', models.BooleanField(default=False)),
                ('homemaker', models.BooleanField(default=False)),
                ('unemployed', models.BooleanField(default=False)),
                ('job_seeker', models.BooleanField(default=False)),
                ('student_only', models.BooleanField(default=False)),
                ('pensioner_rentier', models.BooleanField(default=False)),
                ('retired', models.BooleanField(default=False)),
                ('caregiver', models.BooleanField(default=False)),
                ('community_position', models.BooleanField(default=False)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receives_social_aid', models.BooleanField(default=False)),
                ('social_aid_type', models.CharField(blank=True, max_length=200, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('workplace', models.CharField(blank=True, max_length=200, null=True)),
                ('economy_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Economía de Beneficiario',
                'verbose_name_plural': 'Economía de Beneficiarios',
                'db_table': 'beneficiary_economy',
                'indexes': [models.Index(fields=['beneficiary'], name='beneficiary_benefic_557144_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryEducation',
            fields=[
                ('beneficiary', models.OneToOneField(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='education', serialize=False, to='webAMG.beneficiary')),
                ('education_level', models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('primaria', 'Primaria'), ('basico', 'Básico'), ('diversificado', 'Diversificado'), ('universitario', 'Universitario'), ('otro', 'Otro')], max_length=20, null=True)),
                ('school_attendance', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('a_veces', 'A veces')], max_length=20, null=True)),
                ('education_language', models.CharField(blank=True, choices=[('espanol', 'Español'), ('materno', 'Materno'), ('ambos', 'Ambos'), ('otro', 'Otro')], max_length=20, null=True)),
                ('can_read_write', models.BooleanField(blank=True, null=True)),
                ('years_of_study', models.IntegerField(default=0)),
                ('current_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name', models.CharField(blank=True, max_length=200, null=True)),
                ('has_cellphone', models.BooleanField(default=False)),
                ('has_computer', models.BooleanField(default=False)),
                ('has_internet', models.BooleanField(default=False)),
                ('education_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educación de Beneficiario',
                'verbose_name_plural': 'Educación de Beneficiarios',
                'db_table': 'beneficiary_education',
                'indexes': [models.Index(fields=['beneficiary'], name='beneficiary_benefic_2d102c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryHealth',
            fields=[
                ('beneficiary', models.OneToOneField(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='health', serialize=False, to='webAMG.beneficiary')),
                ('is_pregnant', models.BooleanField(default=False)),
                ('is_breastfeeding', models.BooleanField(default=False)),
                ('has_diabetes', models.BooleanField(default=False)),
                ('has_high_blood_pressure', models.BooleanField(default=False)),
                ('has_low_blood_pressure', models.BooleanField(default=False)),
                ('has_heart_disease', models.BooleanField(default=False)),
                ('has_kidney_disease', models.BooleanField(default=False)),
                ('has_cancer', models.BooleanField(default=False)),
                ('has_respiratory_disease', models.BooleanField(default=False)),
                ('has_language_disability', models.BooleanField(default=False)),
                ('has_hearing_disability', models.BooleanField(default=False)),
                ('has_visual_disability', models.BooleanField(default=False)),
                ('has_physical_disability', models.BooleanField(default=False)),
                ('has_intellectual_disability', models.BooleanField(default=False)),
                ('has_psychosocial_disability', models.BooleanField(default=False)),
                ('health_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Salud de Beneficiario',
                'verbose_name_plural': 'Salud de Beneficiarios',
                'db_table': 'beneficiary_health',
                'indexes': [models.Index(fields=['beneficiary'], name='beneficiary_benefic_92b280_idx')],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryHousing',
            fields=[
                ('beneficiary', models.OneToOneField(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='housing', serialize=False, to='webAMG.beneficiary')),
                ('housing_tenure', models.CharField(blank=True, choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('cedida_prestada', 'Cedida/Prestada'), ('propiedad_comunal', 'Propiedad Comunal'), ('otra', 'Otra')], max_length=20, null=True)),
                ('housing_type', models.CharField(blank=True, choices=[('casa_formal', 'Casa Formal'), ('apartamento', 'Apartamento'), ('cuarto_vecindad', 'Cuarto de Vecindad'), ('rancho', 'Rancho'), ('improvisada', 'Improvisada'), ('colectiva_temporal', 'Colectiva Temporal'), ('otra', 'Otra')], max_length=20, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('floor_material', models.CharField(blank=True, max_length=100, null=True)),
                ('wall_material', models.CharField(blank=True, max_length=100, null=True)),
                ('roof_material', models.CharField(blank=True, max_length=100, null=True)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_piped_water', models.BooleanField(default=False)),
                ('has_sewage', models.BooleanField(default=False)),
                ('water_source', models.CharField(blank=True, max_length=100, null=True)),
                ('drinking_water_source', models.CharField(blank=True, max_length=100, null=True)),
                ('toilet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('waste_disposal', models.CharField(blank=True, max_length=100, null=True)),
                ('housing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vivienda de Beneficiario',
                'verbose_name_plural': 'Vivienda de Beneficiarios',
                'db_table': 'beneficiary_housing',
                'indexes': [models.Index(fields=['beneficiary'], name='beneficiary_benefic_8f7dd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('factura', 'Factura'), ('recibo', 'Recibo'), ('nota_debito', 'Nota de Débito'), ('nota_credito', 'Nota de Crédito'), ('orden_compra', 'Orden de Compra'), ('comprobante_pago', 'Comprobante de Pago'), ('cheque', 'Cheque'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField()),
                ('invoice_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_document_url', models.TextField(blank=True, null=True)),
                ('additional_documents_urls', models.JSONField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budget_executions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_executions', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, db_column='phase_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_executions', to='webAMG.projectphase')),
                ('project', models.ForeignKey(blank=True, db_column='project_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_executions', to='webAMG.project')),
            ],
            options={
                'verbose_name': 'Ejecución Presupuestaria',
                'verbose_name_plural': 'Ejecuciones Presupuestarias',
                'db_table': 'budget_execution',
            },
        ),
        migrations.CreateModel(
            name='EvidenceBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_participations', to='webAMG.beneficiary')),
            ],
            options={
                'verbose_name': 'Beneficiario de Evidencia',
                'verbose_name_plural': 'Beneficiarios de Evidencias',
                'db_table': 'evidence_beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='EvidencePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('photo_order', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Evidencia',
                'verbose_name_plural': 'Fotos de Evidencias',
                'db_table': 'evidence_photos',
            },
        ),
        migrations.CreateModel(
            name='PhaseBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_participations', to='webAMG.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='webAMG.projectphase')),
            ],
            options={
                'verbose_name': 'Beneficiario de Fase',
                'verbose_name_plural': 'Beneficiarios de Fases',
                'db_table': 'phase_beneficiaries',
            },
        ),
        migrations.CreateModel(
            name='ProjectBeneficiary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('beneficiary', models.ForeignKey(db_column='beneficiary_id', on_delete=django.db.models.deletion.CASCADE, to='webAMG.beneficiary')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='webAMG.project')),
            ],
            options={
                'verbose_name': 'Proyecto-Beneficiario',
                'verbose_name_plural': 'Proyectos-Beneficiarios',
                'db_table': 'project_beneficiaries',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, related_name='projects', through='webAMG.ProjectBeneficiary', through_fields=('project', 'beneficiary'), to='webAMG.beneficiary'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_is_acti_3457d5_idx'),
        ),
        migrations.AddField(
            model_name='projectevidence',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectevidence',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='webAMG.project'),
        ),
        migrations.AddField(
            model_name='evidencephoto',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='webAMG.projectevidence'),
        ),
        migrations.AddField(
            model_name='evidencebeneficiary',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='webAMG.projectevidence'),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='webAMG.project'),
        ),
        migrations.AddIndex(
            model_name='activityphoto',
            index=models.Index(fields=['activity'], name='activity_ph_activit_b9ee5f_idx'),
        ),
        migrations.AddIndex(
            model_name='activityphoto',
            index=models.Index(fields=['uploaded_by'], name='activity_ph_uploade_4822aa_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['table_name'], name='audit_log_table_n_84b0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['operation'], name='audit_log_operati_0c5c7f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user'], name='audit_log_user_id_4dac76_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_at'], name='audit_log_perform_3eb331_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['project'], name='budget_exec_project_3bb384_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['phase'], name='budget_exec_phase_i_0881fa_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['invoice_type'], name='budget_exec_invoice_e34ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['invoice_date'], name='budget_exec_invoice_50d026_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['invoice_number'], name='budget_exec_invoice_6dde06_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['category'], name='budget_exec_categor_cb6e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['is_paid'], name='budget_exec_is_paid_dbe28d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['is_approved'], name='budget_exec_is_appr_e27567_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['created_by'], name='budget_exec_created_df4859_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['approved_by'], name='budget_exec_approve_04b803_idx'),
        ),
        migrations.AddIndex(
            model_name='phasebeneficiary',
            index=models.Index(fields=['phase'], name='phase_benef_phase_i_8b7536_idx'),
        ),
        migrations.AddIndex(
            model_name='phasebeneficiary',
            index=models.Index(fields=['beneficiary'], name='phase_benef_benefic_439579_idx'),
        ),
        migrations.AddIndex(
            model_name='phasebeneficiary',
            index=models.Index(fields=['assigned_at'], name='phase_benef_assigne_2b028b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phasebeneficiary',
            unique_together={('phase', 'beneficiary')},
        ),
        migrations.AddIndex(
            model_name='projectbeneficiary',
            index=models.Index(fields=['project'], name='project_ben_project_a31e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbeneficiary',
            index=models.Index(fields=['beneficiary'], name='project_ben_benefic_dd5fb3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbeneficiary',
            index=models.Index(fields=['assigned_at'], name='project_ben_assigne_09cff0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectbeneficiary',
            unique_together={('project', 'beneficiary')},
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['project'], name='project_evi_project_d32582_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['start_date', 'end_date'], name='project_evi_start_d_176268_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['created_by'], name='project_evi_created_2bb1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencephoto',
            index=models.Index(fields=['evidence'], name='evidence_ph_evidenc_e63a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencephoto',
            index=models.Index(fields=['uploaded_by'], name='evidence_ph_uploade_4894b7_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencephoto',
            index=models.Index(fields=['uploaded_at'], name='evidence_ph_uploade_41a046_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencebeneficiary',
            index=models.Index(fields=['evidence'], name='evidence_be_evidenc_59ca0e_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencebeneficiary',
            index=models.Index(fields=['beneficiary'], name='evidence_be_benefic_1cb3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencebeneficiary',
            index=models.Index(fields=['assigned_at'], name='evidence_be_assigne_137512_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidencebeneficiary',
            unique_together={('evidence', 'beneficiary')},
        ),
        migrations.AddIndex(
            model_name='projectmaterial',
            index=models.Index(fields=['project'], name='project_mat_project_ca62ad_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmaterial',
            index=models.Index(fields=['purchase_date'], name='project_mat_purchas_13aa51_idx'),
        ),
    ]
