# Generated by Django 6.0.1 on 2026-02-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webAMG', '0005_sync_existing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityphoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budgetexecution',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidencebeneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidencephoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phasebeneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phaseevidence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phaseevidencebeneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phaseevidencephoto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectbeneficiary',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectevidence',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectphase',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='activityphoto',
            index=models.Index(fields=['is_active'], name='activity_ph_is_acti_d1849f_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetexecution',
            index=models.Index(fields=['is_active'], name='budget_exec_is_acti_b77bea_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyactivity',
            index=models.Index(fields=['is_active'], name='daily_activ_is_acti_398ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencebeneficiary',
            index=models.Index(fields=['is_active'], name='evidence_be_is_acti_799b85_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencephoto',
            index=models.Index(fields=['is_active'], name='evidence_ph_is_acti_2a7a5c_idx'),
        ),
        migrations.AddIndex(
            model_name='phasebeneficiary',
            index=models.Index(fields=['is_active'], name='phase_benef_is_acti_94afb2_idx'),
        ),
        migrations.AddIndex(
            model_name='phaseevidence',
            index=models.Index(fields=['is_active'], name='phase_evide_is_acti_f9a630_idx'),
        ),
        migrations.AddIndex(
            model_name='phaseevidencebeneficiary',
            index=models.Index(fields=['is_active'], name='phase_evide_is_acti_7088ee_idx'),
        ),
        migrations.AddIndex(
            model_name='phaseevidencephoto',
            index=models.Index(fields=['is_active'], name='phase_evide_is_acti_9c89cf_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbeneficiary',
            index=models.Index(fields=['is_active'], name='project_ben_is_acti_be09a1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectevidence',
            index=models.Index(fields=['is_active'], name='project_evi_is_acti_45168d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmaterial',
            index=models.Index(fields=['is_active'], name='project_mat_is_acti_bcff70_idx'),
        ),
        migrations.AddIndex(
            model_name='projectphase',
            index=models.Index(fields=['is_active'], name='project_pha_is_acti_a782b7_idx'),
        ),
    ]
